---
name: Super linter

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  lint:
    uses: validatedpatterns/github-actions-library/.github/workflows/superlinter.yml@v1
    with:
      sl_env: |
        VALIDATE_BIOME_FORMAT=false
        VALIDATE_KUBERNETES_KUBECONFORM=false
        VALIDATE_TRIVY=false
        VALIDATE_YAML=false
        VALIDATE_YAML_PRETTIER=false
